In [1]:
"""
Notebook untuk mengambil data berita dari Elasticsearch dan mempersiapkan dataset NER.
"""

'\nNotebook untuk mengambil data berita dari Elasticsearch dan mempersiapkan dataset NER.\n'

In [2]:
from elasticsearch import Elasticsearch
import pandas as pd
from dotenv import load_dotenv
import os

load_dotenv()

True

In [3]:
ES_HOST = os.getenv("ELASTICSEARCH_HOST")
ES_USER = os.getenv("ELASTICSEARCH_USER")
ES_PASSWORD = os.getenv("ELASTICSEARCH_PASSWORD")

es = Elasticsearch(
    ES_HOST,
    basic_auth=(ES_USER, ES_PASSWORD),
    request_timeout=60
)

res = es.search(
    index="news_2025.07",
    query={"match_all": {}},
    size=1000
)

docs = [hit["_source"] for hit in res["hits"]["hits"]]
df = pd.DataFrame(docs)

In [13]:
df

,authors,created,favicon,fulltext,hashtitle,jenis,keywords,language,link,media_url,...,geo,summarization,published_to_es,is_updated,known_by_police,published_all,username,subs_name,cluster,cluster_name
0,[LIL],2025-07-02T21:05:23.638724+07:00,,Sukabumihitz – K-Pop Demon Hunters adalah film...,cac18e1607884f9d4fe7e750b1078c080bb7f052,News Non Dewanpers,"[pop, soundtrack, paket, demon, hunters, visua...",id,https://sukabumihitz.com/hiburan/film/k-pop-de...,https://sukabumihitz.com/wp-content/uploads/20...,...,[],,2025-07-02T21:16:10.563714+07:00,False,,2025-07-02T11:21:11+07:00,sukabumihitz.com,subs_news_2,NaN,NaN
1,[M Iqbal],2025-07-02T21:07:53.879370+07:00,,"02 Jul 2025, 08:18 WIB Suasana sekitar Pasar ...",fb5561243439b9dbcf3c9e9dc8de3a98aa6b4d3f,News Non Dewanpers,"[dilarang, ciputat, parkir, arah, kendaraan, 2...",id,https://banten.idntimes.com/news/banten/sistem...,https://image.idntimes.com/post/20250702/uploa...,...,"[{'lat': -6.1761924, 'lon': 106.6382161}]",,2025-07-02T21:17:41.985100+07:00,False,,2025-07-02T07:00:00+07:00,idntimes.com,subs_news_3,NaN,NaN
2,[Patricia Kahanap],2025-07-02T21:14:47.254861+07:00,,"MANILA, Philippines — When he found out one mo...",7074311e0e438f4f7a7ed7810a84b2e2cdfeb42a,News Non Dewanpers,"[lot, history, dreams, community, payne, liam,...",en,https://www.rappler.com/entertainment/how-liam...,https://www.rappler.com/tachyon/2024/10/liam-p...,...,[],,2025-07-02T21:17:45.138139+07:00,False,,2024-10-19T07:58:36+07:00,rappler.com,subs_news_13,NaN,NaN
3,"[Sopian Simanjuntak, Wahana News]",2025-07-01T14:14:32.196899+07:00,,"WAHANANEWS.CO, Jakarta - Skandal korupsi pemba...",bcf88c7be141aafa4717e1c75c8faf61d2281566,DKI Jakarta,"[kejutkan, tersangka, terseret, suap, rp2, mil...",id,https://wahananews.co/polhukam/ott-kpk-kejutka...,https://wahananews.co/photo/thumbs/wahananews/...,...,"[{'lat': -1.2046012, 'lon': 100.5740077}]",,2025-07-02T21:17:45.287016+07:00,True,,2025-06-29T02:24:38+07:00,wahananews.co,subs_news_12,NaN,NaN
4,"[Bawi Kogoya, Wahana News Papua]",2025-07-01T14:14:04.966503+07:00,,"Papua.WahanaNews.co, Jayapura – Keberhasilan B...",5b9071c1224fbd0027e1e87c1244002293883880,News Non Dewanpers,"[penuhi, janjinya, putra, dilantik, karel, pol...",id,https://papua.wahananews.co/serba-serbi/kapolr...,https://wahananews.co/photo/thumbs/papua.wahan...,...,"[{'lat': -2.5387539, 'lon': 140.7037389}, {'la...",,2025-07-02T21:18:38.389976+07:00,True,,2023-12-23T17:22:29+07:00,wahananews.co,subs_news_12,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,[Redaksi],2025-07-04T04:06:39.838112+07:00,,(KANALACEH.COM) – Air kelapa memiliki banyak m...,026a32443fd20e70d012143c07010940fba496fa,News Non Dewanpers,"[daftar, kelapa, air, yang, minum, orang, tida...",en,https://www.kanalaceh.com/2025/04/10/daftar-ke...,https://www.kanalaceh.com/wp-content/uploads/2...,...,[],,2025-07-04T04:11:59.175043+07:00,True,,2025-04-10T07:00:00+07:00,kanalaceh.com,subs_news_12,NaN,NaN
996,"[Rusman Afrizal, : Rusman Afrizal, koranrb.id]",2025-07-04T04:05:55.105274+07:00,,"BINTUHAN - Hingga Juli 2025, Dinas Kesehatan (...",ba052b1ce0aefa71dbea0049d1e807a804e1317d,News Non Dewanpers,"[lakukan, balita, penimbangan, pengukuran, 313...",id,https://harianrakyatbengkulu.bacakoran.co/read...,https://harianrakyatbengkulu.bacakoran.co/uplo...,...,"[{'lat': -4.5905275, 'lon': 103.36526129380955}]",,2025-07-04T04:11:55.674522+07:00,True,,2025-07-03T21:27:00+07:00,bacakoran.co,subs_news_11,NaN,NaN
997,[Pacitanku],2025-07-04T04:09:23.101300+07:00,,"Pacitanku.com, PACITAN – Bupati Pacitan Indrat...",a0c344f846c7df9224c0c9d5ded6f60e13385190,News Non Dewanpers,"[cerita, pengalaman, murid, smp, bupati, pacit...",id,https://pacitanku.com/2023/01/31/bertemu-ratus...,https://pacitanku.com/wp-content/uploads/2023/...,...,[],,2025-07-04T04:14:28.192561+07:00,False,,2023-01-31T07:00:00+07:00,pacitanku.com,subs_news_9,NaN,NaN
998,[Redaksi News],2025-07-04T04:06:59.023799+07:00,,"BATAM, Peristiwanusantara.com – Harris Resort ...",4983b0fcf133232cec52831b690a4adb6c94dcd9,Kepulauan Riau,"[baru, 2021, menghadirkan, beragam, menarik, h...",,https://www.peristiwanusantara.com/2020/12/men...,https://blogger.googleusercontent.com/img/b/R2...,...,"[{'lat': 1.1030815, 'lon': 104.0383696}]",,2025-07-04T04:14:35.601658+07:00,True,,2020-12-24T07:00:00+07:00,peristiwanusantara.com,subs_news_18,NaN,NaN
999,"[Gilang Adrian, Wahana News]",2025-07-04T04:07:34.886708+07:00,,"WAHANANEWS.CO, Jakarta - Indonesia dijadwalkan...",3abee1e68c60aa59eb4a566b2d5f595edfbf2291,DKI Jakarta,"[hadirkan, sportivitas, deaf, 2025, sea, games...",id,https://wahananews.co/olahraga/sea-deaf-games-...,https://wahananews.co/photo/thumbs/wahananews/...,...,[],,2025-07-04T04:14:29.349556+07:00,False,,2025-06-23T22:00:59+07:00,wahananews.co,subs_news_12,NaN,NaN

In [6]:
news_df = df[['hashtitle', 'fulltext']]

In [10]:
news_df.head()

,hashtitle,fulltext
0,cac18e1607884f9d4fe7e750b1078c080bb7f052,Sukabumihitz – K-Pop Demon Hunters adalah film...
1,fb5561243439b9dbcf3c9e9dc8de3a98aa6b4d3f,"02 Jul 2025, 08:18 WIB Suasana sekitar Pasar ..."
2,7074311e0e438f4f7a7ed7810a84b2e2cdfeb42a,"MANILA, Philippines — When he found out one mo..."
3,bcf88c7be141aafa4717e1c75c8faf61d2281566,"WAHANANEWS.CO, Jakarta - Skandal korupsi pemba..."
4,5b9071c1224fbd0027e1e87c1244002293883880,"Papua.WahanaNews.co, Jayapura – Keberhasilan B..."

In [12]:
news_df['fulltext'][0]

'Sukabumihitz – K-Pop Demon Hunters adalah film animasi musikal Amerika yang dirilis oleh Netflix pada Juni 2025, diproduksi oleh Sony Pictures Animation. Film ini menghadirkan konsep yang benar-benar segar yang menggabungkan budaya K-Pop dengan aksi fantasi tentang pemburu monster. Disutradarai oleh Maggie Kang dan Chris Appelhans, film ini berhasil mencuri perhatian dengan visual yang memukau, lagu-lagu yang adiktif, dan cerita yang penuh humor serta emosi.  Sinopsis Film Animasi K-Pop Demon Hunters  Film ini mengisahkan tentang Huntrix, sebuah grup K-Pop wanita yang terdiri dari tiga anggota: Rumi (Arden Cho), Mira (May Hong), dan Zoey (Ji-young Yoo). Di balik sorotan panggung dan gemerlap ketenaran, mereka menyimpan rahasia besar. Mereka adalah pemburu monster yang bertugas menjaga dunia dari ancaman supranatural yang dipimpin oleh raja dari para monster, Gwi-Ma (Lee Byung-hun).  Warisan ini telah ada dari generasi ke generasi. Para penyanyi wanita menggunakan suara mereka untuk mempertahankan Honmoon, sebuah penghalang magis yang memisahkan dunia manusia dari dunia monster.  Namun, tantangan terbesar muncul ketika Gwi-Ma mengirimkan boyband monster bernama Saja Boys, dengan leader bernama Jinu (Ahn Hyo-seop). Mereka melemahkan Honmoon dengan mencuri jiwa penggemar Huntrix. Konflik semakin rumit ketika Rumi, yang menyimpan rahasia tentang asal-usulnya sebagai keturunan manusia-monster, mulai membentuk ikatan tak terduga dengan Jinu. Cerita ini memadukan aksi, musikal, dan drama dengan sentuhan budaya Korea yang kental.  Visual dan Animasi yang Terinspirasi Dari Spider-Man: Into the Spider-Verse  Salah satu daya tarik utama K-Pop Demon Hunters adalah animasinya yang memukau hasil garapan Sony Pictures Animation, yang terkenal lewat Spider-Man: Into the Spider-Verse. Film ini mengadopsi gaya visual yang terinspirasi dari pencahayaan konser, fotografi editorial, drama Korea, dan anime. Setiap frame dirancang dengan detail yang luar biasa. Mulai dari kostum karakter yang mencerminkan kepribadian mereka hingga adegan aksi yang dinamis dan penuh warna.  Adegan pertarungan, seperti saat Huntrix melawan monster di pesawat pribadi sambil menyanyikan “How It’s Done”, adalah contoh sempurna bagaimana film ini memadukan koreografi aksi dengan ritme musik. Efek visual seperti ledakan konfeti saat pertarungan dengan monster atau perubahan bentuk pupil mata Zoey menjadi hati saat melihat Saja Boys menambah elemen komedi dalam film.  Soundtrack yang Melekat Kuat  Musik adalah jantung dari K-Pop Demon Hunters. Soundtrack-nya menampilkan lagu-lagu orisinal dari talenta seperti Jeongyeon, Jihyo, dan Chaeyoung dari TWICE. Lagu-lagu seperti “Takedown”, “Golden”, dan “How It’s Done” tidak hanya catchy, tetapi juga terintegrasi dengan cerita. Lagu-lagu ini memperkuat emosi dan aksi para karakter dalam film. “Golden”, misalnya, menjadi lagu harapan Huntrix yang menggambarkan semangat mereka, sementara lagu “Your Idol” Saja Boys memberikan dimensi emosional pada karakter antagonis.  Banyak penonton yang mengaku langsung menambahkan lagu-lagu ini ke playlist Spotify mereka, dengan beberapa menyebutnya “wall-to-wall bangers”. Bahkan bagi yang bukan penggemar K-Pop, lagu-lagu ini tetap terasa menarik karena produksi yang berkualitas tinggi dan lirik yang relatable.   Tema dan Pesan Film yang Lebih dari Sekadar Hiburan  Di balik premis yang terdengar “silly” tentang girlband pemburu monster, K-Pop Demon Hunters menyampaikan pesan yang kuat tentang penerimaan diri, persahabatan, dan tekanan industri K-Pop. Film ini secara halus mengkritik ekspektasi perfeksionisme dalam budaya idola, di mana para bintang harus tampak sempurna. Kisah Rumi yang berjuang dengan identitasnya sebagai setengah monster mencerminkan perjuangan universal untuk menerima ketidaksempurnaan.  Meskipun mendapat banyak pujian, K-Pop Demon Hunters bukannya tanpa cela. Beberapa penonton merasa bahwa ceritanya terlalu sederhana seperti mekanisme Honmoon atau asal-usul kekuatan Huntrix, kurang detail. Ending film ini juga menuai sedikit kritik karena terasa terlalu terburu-buru atau meninggalkan beberapa pertanyaan tanpa jawaban. Namun banyak juga yang melihatnya sebagai pintu yang sangat potensial untuk sebuah sekuel.  K-Pop Demon Hunters adalah sebuah kejutan yang menyenangkan di tahun 2025. Dengan premis unik, visual menarik, dan soundtrack yang adiktif, film ini berhasil menjadi lebih dari sekadar hiburan ringan. Meskipun ceritanya sederhana dan beberapa elemen kurang tergali, kekuatan film ini terletak pada eksekusi yang penuh semangat, humor yang cerdas, dan pesan emosional yang menyentuh. '

In [11]:
news_df.to_csv("../data/label studio/100_news_unlabeled.csv", index=False)

In [ ]:
news_summary = df[['hashtitle','summary', 'ners']]

def extract_entity(ners_dict, entity_type):
    try:
        if isinstance(ners_dict, dict):
            return ners_dict.get(entity_type, [])
        elif isinstance(ners_dict, str):
            ners_dict = ast.literal_eval(ners_dict)
            return ners_dict.get(entity_type, [])
        else:
            return []
    except:
        return []

news_summary['location'] = news_summary['ners'].apply(lambda x: extract_entity(x, 'location'))
news_summary['organization'] = news_summary['ners'].apply(lambda x: extract_entity(x, 'organization'))
news_summary['person'] = news_summary['ners'].apply(lambda x: extract_entity(x, 'person'))

news_summary.drop('ners', axis=1)

In [ ]:
# Rename kolom
news_summary = news_summary.rename(columns={
    'location': 'old_LOC',
    'organization': 'old_ORG',
    'person': 'old_PER'
})

news_summary['gt_PER'] = [[] for _ in range(len(news_summary))]
news_summary['gt_LOC'] = [[] for _ in range(len(news_summary))]
news_summary['gt_ORG'] = [[] for _ in range(len(news_summary))]

news_summary = news_summary.drop(columns=['old_LOC', 'old_ORG', 'old_PER'], errors='ignore')

In [ ]:
news_summary

In [ ]:
news_summary.drop(columns=['hashtitle', 'ners', 'gt_PER', 'gt_LOC', 'gt_ORG'], )

In [ ]:
news_summary.to_csv('news_2025.csv', index=False)